
ALTER TABLESPACE MEM_TEMP_TBS ADD MEMORY 'system_temp_01' SIZE 1G;
--ALTER TABLESPACE MEM_TEMP_TBS ADD MEMORY 'system_temp_02' SIZE 1G;
--ALTER TABLESPACE MEM_TEMP_TBS ADD MEMORY 'system_temp_03' SIZE 1G;

ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'system_data_01.dbf' SIZE 1G;
--ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db01/system_data_01.dbf' SIZE 1G;
--ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db02/system_data_02.dbf' SIZE 1G;
--ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db03/system_data_03.dbf' SIZE 1G;
--ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db04/system_data_04.dbf' SIZE 1G;

