
-- DATABASE
DROP DATABASE IF EXISTS TESTDB1;
CREATE DATABASE TESTDB1;

ALTER DATABASE TESTDB1
DEFAULT CHARACTER SET = 'utf8'
;

ALTER DATABASE TESTDB1
DEFAULT COLLATE = 'utf8_general_ci'
;



-- TABLESPACE
CREATE TABLESPACE TS1 ADD DATAFILE 'ts1.idb' ENGINE=INNODB;


-- GTID
SELECT @@GLOBAL.GTID_OWNED;
SET @@GLOBAL.GTID_MODE = OFF;
SET @@GLOBAL.GTID_MODE = ON_PERMISSIVE;
SET @@GLOBAL.GTID_MODE = OFF_PREMISSIVE;
SET @@GLOBAL.ENFORCE_GTID_CONSISTENCY = OFF;


-- INNODB BUFFER POOL SIZE ONLINE
SET @@GLOBAL.innodb_buffer_pool_size=134217728;


