

ALTER TABLESPACE MEM_TEMP_TBS ADD MEMORY   'temp01' SIZE 1G;
ALTER TABLESPACE MEM_TEMP_TBS ADD MEMORY   'temp02' SIZE 1G;
ALTER TABLESPACE MEM_TEMP_TBS ADD MEMORY   'temp03' SIZE 1G;

ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db01/data01.dbf' SIZE 1G;
ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db02/data02.dbf' SIZE 1G;
ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db03/data03.dbf' SIZE 1G;
ALTER TABLESPACE MEM_DATA_TBS ADD DATAFILE 'db04/data04.dbf' SIZE 1G;

