
# path , etc
CHLEE_HOME=$HOME/.chlee
if [ -d "$CHLEE_HOME" ]; then
    export PATH=$PATH:$CHLEE_HOME/bin
    export PATH=$PATH:$CHLEE_HOME/dba/goldilocks
    export PATH=$PATH:$CHLEE_HOME/dba/mysql
fi


OSTYPE=`uname`
export PATH=.:$PATH

set -o vi

# for stop escaping when during tab key
if [ ${SHELL} = '/bin/bash' ]; then
	if [ ${BASH_VERSION:0:1} -ge 4 ]; then

		shopt -s direxpand
	fi
fi

export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\n\$ "
export SVN_EDITOR=vim
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib64

ulimit -c unlimited

# alias
alias p='python'

# Git
#export GIT_SSL_NO_VERIFY=0

# GLIESE-SUNDB-GOLDILOCKS COMMON
export PRODUCT_HOME=$HOME/workspace/sundb/product
export PATH=/bin:/usr/bin:/usr/local/bin:/sbin:$HOME/bin:$PRODUCT_HOME/TestTool/Unit/dev/bin:$PATH
export PATH=$PATH:$PRODUCT_HOME/TestTool/Embedded/dev/bin

# GLIESE
export DB_HOME=$PRODUCT_HOME/Gliese/home
export DB_DATA=$PRODUCT_HOME/Gliese/home
export CLASSPATH=$CLASSPATH:$DB_HOME/lib
export GLIESE_SHARED_MEMORY_STATIC_KEY=542353
export PATH=$DB_HOME/bin:$PATH

# SUNDB
export SUNDB_HOME=$PRODUCT_HOME/Gliese/home
export SUNDB_DATA=$PRODUCT_HOME/Gliese/home
export CLASSPATH=$CLASSPATH:$SUNDB_HOME/lib
export SUNDB_SHARED_MEMORY_STATIC_KEY=542353
export PATH=$SUNDB_HOME/bin:$PATH

# GOLDILOCKS
export GOLDILOCKS_HOME=$PRODUCT_HOME/Gliese/home
export GOLDILOCKS_DATA=$PRODUCT_HOME/Gliese/home
export CLASSPATH=$CLASSPATH:$GOLDILOCKS_HOME/lib
export GOLDILOCKS_SHARED_MEMORY_STATIC_KEY=542353
export PATH=$GOLDILOCKS_HOME/bin:$PATH

# for database utillity env-variable
if [ -f "$GOLDILOCKS_HOME/bin/gsql" ]; then
	GSQLBIN=gsql
else
	GSQLBIN=gsqlnet	
fi

alias gl='$GSQLBIN   test test '
alias gls='$GSQLBIN  sys gliese --as sysdba '

export GSQL_UID="test"
export GSQL_PWD="test"
export GSQL="$GSQLBIN $GSQL_UID $GSQL_PWD "


# for jdbc compile

if [ $OSTYPE = "Darwin" ]; then
export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
else
export JAVA_HOME=$HOME/jdk1.6.0_27
export JAVA5=$HOME/jdk1.5.0_22
fi
export PATH=$PATH:$JAVA_HOME/bin

# SOLACE
export SOLACE_HOME=$HOME/solace/solclient
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DB_HOME/lib:$HOME/solace/solclient/lib

# ORACLE
export ORACLE_HOME=/data/oracle/app/oracle/product/12.1.0/dbhome_2
export ORACLE_SID=orcl
export NLS_LANG=KOREAN_KOREA.UTF8
export PATH=$ORACLE_HOME/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ORACLE_HOME/lib
export ORACLE_DRIVER=$ORACLE_HOME/lib/libsqora.so.12.1
alias gg='gsqlnet test test --dsn orcl --driver $ORACLE_DRIVER'

# msssql
export MSSQL_HOME=/opt/mssql
export PATH=$PATH:/opt/mssql-tools/bin
alias ms="sqlcmd -S localhost -U SA -P 'cjfl@1234'"

# postgresql
export POSTGRES_HOME=/home/chlee/workspace/postgresql-12.3
export PGLIB=$POSTGRES_HOME/lib
export PGDATA=$POSTGRES_HOME/data
export MANPATH=$MANPATH:$POSTGRES_HOME/man
export PATH=$POSTGRES_HOME/bin:$PATH:$HOME/.local/bin:$HOME/bin
ulimit -n 65535

